# Generated by Django 5.0.6 on 2024-05-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('author_id', models.CharField(max_length=50)),
                ('slug_nombre', models.SlugField(blank=True, unique=True)),
                ('slug_author_id', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('author_id', models.CharField(max_length=50)),
                ('slug_descripcion', models.SlugField(blank=True)),
                ('slug_author_id', models.SlugField(blank=True)),
                ('slug_lista_id', models.SlugField(blank=True)),
                ('estado', models.CharField(choices=[('TODO', 'Pendiente'), ('DONE', 'Completada'), ('INIT', 'Iniciada')], default='TODO', max_length=4)),
                ('lista_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listas.lista')),
            ],
        ),
    ]
