# Generated by Django 5.0.6 on 2024-05-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('TODO', 'Pendiente'), ('DONE', 'Completada'), ('INIT', 'Iniciada')], default='TODO', max_length=4)),
                ('author_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
