# Generated by Django 5.0.6 on 2024-05-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listas', '0002_lista_tarea_lista_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='author_id',
            field=models.CharField(max_length=50),
        ),
    ]
